# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasgoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.IntegerField()),
                ('type', models.CharField(choices=[('87', 'Unleaded'), ('89', 'Plus'), ('91', 'Premium')], max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='GasgoApp.Driver')),
                ('filler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='GasgoApp.Filler')),
            ],
        ),
    ]
