# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasgoApp', '0005_auto_20190924_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='null', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='gallons',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('87', 'Unleaded'), ('89', 'Plus'), ('91', 'Premium')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
