# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GasgoApp', '0007_auto_20190926_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
